# Docker Ingress Point - Standalone Traefik Configuration
# Environment variables are loaded from .env file by default
# See README.md for detailed documentation
#
# This configuration provides:
# - Traefik reverse proxy with HTTP/HTTPS access (80, 443, 8081)
# - Automatic SSL certificates via Let's Encrypt with Cloudflare DNS challenge
# - Docker provider for service discovery
# - Multi-app network discovery and routing
#
# Deploy with: docker-compose up -d

version: "3.8"

services:
  traefik:
    container_name: "${CONTAINER_NAME_PREFIX:-traefik}-ingress"
    image: "traefik:latest"
    # Run in privileged mode for Docker socket access
    privileged: true
    environment:
      - TZ=${TZ:-America/New_York}
      # Cloudflare API credentials for DNS challenge
      # Method 1: API Token (recommended - more secure)
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:-}
      # Method 2: Global API Key (fallback if API Token not provided)
      - CF_API_EMAIL=${CF_API_EMAIL:-}
      - CF_API_KEY=${CF_API_KEY:-}
    volumes:
      # Docker socket access for container discovery
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # Shared certificate storage
      - "acme-certificates:/acme:rw"
    command:
      # Enable dashboard and API
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Set to false in production for security
      # Docker provider configuration
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=tcp://100.101.14.75:2375"
      - "--providers.docker.watch=true"
      - "--providers.docker.useBindPortIP=false"
      # Ping configuration
      - "--ping=true"
      - "--ping.entryPoint=dashboard"
      # Entry points
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:8081"
      # Global HTTP to HTTPS redirect
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # Logging
      - "--log.level=${TRAEFIK_LOG_LEVEL:-INFO}"
      - "--accesslog=${TRAEFIK_ACCESS_LOG:-false}"
      # ACME (Let's Encrypt) configuration
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
    restart: unless-stopped
    labels:
      - 'traefik.enable=true'
      # Dashboard configuration
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST:-traefik.localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=dashboard"

networks:
  # Traefik public network for service discovery
  traefik-public:
    driver: bridge
    name: traefik_public

volumes:
  # ACME certificate storage
  acme-certificates:
    name: "${CONTAINER_NAME_PREFIX:-traefik}-acme-certificates"
    driver: local
    driver_opts:
      type: ${ACME_VOLUME_TYPE:-}
      o: ${ACME_VOLUME_OPTIONS:-}
      device: ${CONFIG_BASE:-/data/traefik}/acme